# .github/workflows/main.yml

name: CaptionBuddy CI/CD

on:
  push:
    branches:
      - main # This workflow runs on every push to the main branch.

jobs:
  deploy_to_testflight:
    name: Build, Test, and Deploy to TestFlight
    runs-on: macos-latest
env: # <-- Add this section if it doesn't exist
      AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      # This step creates the api_key.json file from a GitHub secret.
      - name: Decode App Store Connect API Key
        env:
          APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: echo $APP_STORE_CONNECT_API_KEY_BASE64 | base64 --decode > fastlane/api_key.json

      # Install and run Fastlane
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Or a recent version
      - run: bundle install
      - run: bundle exec fastlane beta